version: '3.8'

services:
  api:
    image: ingresso.go-api:latest
    container_name: ingresso.go-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile